import { Injectable } from '@angular/core';

export interface Country {
  code: string;
  name: string;
}

export interface Nationality {
  code: string;
  name: string;
}

@Injectable({
  providedIn: 'root'
})
export class LocationService {
  private readonly countries: Country[] = [
    { code: 'AF', name: 'Afghanistan' },
    { code: 'AL', name: 'Albania' },
    { code: 'DZ', name: 'Algeria' },
    { code: 'AS', name: 'American Samoa' },
    { code: 'AD', name: 'Andorra' },
    { code: 'AO', name: 'Angola' },
    { code: 'AI', name: 'Anguilla' },
    { code: 'AQ', name: 'Antarctica' },
    { code: 'AG', name: 'Antigua and Barbuda' },
    { code: 'AR', name: 'Argentina' },
    { code: 'AM', name: 'Armenia' },
    { code: 'AW', name: 'Aruba' },
    { code: 'AU', name: 'Australia' },
    { code: 'AT', name: 'Austria' },
    { code: 'AZ', name: 'Azerbaijan' },
    { code: 'BS', name: 'Bahamas' },
    { code: 'BH', name: 'Bahrain' },
    { code: 'BD', name: 'Bangladesh' },
    { code: 'BB', name: 'Barbados' },
    { code: 'BY', name: 'Belarus' },
    { code: 'BE', name: 'Belgium' },
    { code: 'BZ', name: 'Belize' },
    { code: 'BJ', name: 'Benin' },
    { code: 'BM', name: 'Bermuda' },
    { code: 'BT', name: 'Bhutan' },
    { code: 'BO', name: 'Bolivia' },
    { code: 'BA', name: 'Bosnia and Herzegovina' },
    { code: 'BW', name: 'Botswana' },
    { code: 'BV', name: 'Bouvet Island' },
    { code: 'BR', name: 'Brazil' },
    { code: 'BN', name: 'Brunei' },
    { code: 'BG', name: 'Bulgaria' },
    { code: 'BF', name: 'Burkina Faso' },
    { code: 'BI', name: 'Burundi' },
    { code: 'KH', name: 'Cambodia' },
    { code: 'CM', name: 'Cameroon' },
    { code: 'CA', name: 'Canada' },
    { code: 'CV', name: 'Cape Verde' },
    { code: 'KY', name: 'Cayman Islands' },
    { code: 'CF', name: 'Central African Republic' },
    { code: 'TD', name: 'Chad' },
    { code: 'CL', name: 'Chile' },
    { code: 'CN', name: 'China' },
    { code: 'CX', name: 'Christmas Island' },
    { code: 'CC', name: 'Cocos Islands' },
    { code: 'CO', name: 'Colombia' },
    { code: 'KM', name: 'Comoros' },
    { code: 'CG', name: 'Congo' },
    { code: 'CD', name: 'Congo (Democratic Republic)' },
    { code: 'CK', name: 'Cook Islands' },
    { code: 'CR', name: 'Costa Rica' },
    { code: 'HR', name: 'Croatia' },
    { code: 'CU', name: 'Cuba' },
    { code: 'CY', name: 'Cyprus' },
    { code: 'CZ', name: 'Czech Republic' },
    { code: 'DK', name: 'Denmark' },
    { code: 'DJ', name: 'Djibouti' },
    { code: 'DM', name: 'Dominica' },
    { code: 'DO', name: 'Dominican Republic' },
    { code: 'EC', name: 'Ecuador' },
    { code: 'EG', name: 'Egypt' },
    { code: 'SV', name: 'El Salvador' },
    { code: 'GQ', name: 'Equatorial Guinea' },
    { code: 'ER', name: 'Eritrea' },
    { code: 'EE', name: 'Estonia' },
    { code: 'ET', name: 'Ethiopia' },
    { code: 'FK', name: 'Falkland Islands' },
    { code: 'FO', name: 'Faroe Islands' },
    { code: 'FJ', name: 'Fiji' },
    { code: 'FI', name: 'Finland' },
    { code: 'FR', name: 'France' },
    { code: 'GF', name: 'French Guiana' },
    { code: 'PF', name: 'French Polynesia' },
    { code: 'TF', name: 'French Southern Territories' },
    { code: 'GA', name: 'Gabon' },
    { code: 'GM', name: 'Gambia' },
    { code: 'GE', name: 'Georgia' },
    { code: 'DE', name: 'Germany' },
    { code: 'GH', name: 'Ghana' },
    { code: 'GI', name: 'Gibraltar' },
    { code: 'GR', name: 'Greece' },
    { code: 'GL', name: 'Greenland' },
    { code: 'GD', name: 'Grenada' },
    { code: 'GP', name: 'Guadeloupe' },
    { code: 'GU', name: 'Guam' },
    { code: 'GT', name: 'Guatemala' },
    { code: 'GG', name: 'Guernsey' },
    { code: 'GN', name: 'Guinea' },
    { code: 'GW', name: 'Guinea-Bissau' },
    { code: 'GY', name: 'Guyana' },
    { code: 'HT', name: 'Haiti' },
    { code: 'HK', name: 'Hong Kong' },
    { code: 'HU', name: 'Hungary' },
    { code: 'IS', name: 'Iceland' },
    { code: 'IN', name: 'India' },
    { code: 'ID', name: 'Indonesia' },
    { code: 'IR', name: 'Iran' },
    { code: 'IQ', name: 'Iraq' },
    { code: 'IE', name: 'Ireland' },
    { code: 'IM', name: 'Isle of Man' },
    { code: 'IL', name: 'Israel' },
    { code: 'IT', name: 'Italy' },
    { code: 'CI', name: 'Ivory Coast' },
    { code: 'JM', name: 'Jamaica' },
    { code: 'JP', name: 'Japan' },
    { code: 'JE', name: 'Jersey' },
    { code: 'JO', name: 'Jordan' },
    { code: 'KZ', name: 'Kazakhstan' },
    { code: 'KE', name: 'Kenya' },
    { code: 'KI', name: 'Kiribati' },
    { code: 'KP', name: 'North Korea' },
    { code: 'KR', name: 'South Korea' },
    { code: 'KW', name: 'Kuwait' },
    { code: 'KG', name: 'Kyrgyzstan' },
    { code: 'LA', name: 'Laos' },
    { code: 'LV', name: 'Latvia' },
    { code: 'LB', name: 'Lebanon' },
    { code: 'LS', name: 'Lesotho' },
    { code: 'LR', name: 'Liberia' },
    { code: 'LY', name: 'Libya' },
    { code: 'LI', name: 'Liechtenstein' },
    { code: 'LT', name: 'Lithuania' },
    { code: 'LU', name: 'Luxembourg' },
    { code: 'MO', name: 'Macao' },
    { code: 'MK', name: 'Macedonia' },
    { code: 'MG', name: 'Madagascar' },
    { code: 'MW', name: 'Malawi' },
    { code: 'MY', name: 'Malaysia' },
    { code: 'MV', name: 'Maldives' },
    { code: 'ML', name: 'Mali' },
    { code: 'MT', name: 'Malta' },
    { code: 'MH', name: 'Marshall Islands' },
    { code: 'MQ', name: 'Martinique' },
    { code: 'MR', name: 'Mauritania' },
    { code: 'MU', name: 'Mauritius' },
    { code: 'YT', name: 'Mayotte' },
    { code: 'MX', name: 'Mexico' },
    { code: 'FM', name: 'Micronesia' },
    { code: 'MD', name: 'Moldova' },
    { code: 'MC', name: 'Monaco' },
    { code: 'MN', name: 'Mongolia' },
    { code: 'ME', name: 'Montenegro' },
    { code: 'MA', name: 'Morocco' },
    { code: 'MZ', name: 'Mozambique' },
    { code: 'MM', name: 'Myanmar' },
    { code: 'NA', name: 'Namibia' },
    { code: 'NR', name: 'Nauru' },
    { code: 'NP', name: 'Nepal' },
    { code: 'NL', name: 'Netherlands' },
    { code: 'AN', name: 'Netherlands Antilles' },
    { code: 'NC', name: 'New Caledonia' },
    { code: 'NZ', name: 'New Zealand' },
    { code: 'NI', name: 'Nicaragua' },
    { code: 'NE', name: 'Niger' },
    { code: 'NG', name: 'Nigeria' },
    { code: 'NU', name: 'Niue' },
    { code: 'NF', name: 'Norfolk Island' },
    { code: 'MP', name: 'Northern Mariana Islands' },
    { code: 'NO', name: 'Norway' },
    { code: 'OM', name: 'Oman' },
    { code: 'PK', name: 'Pakistan' },
    { code: 'PW', name: 'Palau' },
    { code: 'PS', name: 'Palestine' },
    { code: 'PA', name: 'Panama' },
    { code: 'PG', name: 'Papua New Guinea' },
    { code: 'PY', name: 'Paraguay' },
    { code: 'PE', name: 'Peru' },
    { code: 'PH', name: 'Philippines' },
    { code: 'PN', name: 'Pitcairn Islands' },
    { code: 'PL', name: 'Poland' },
    { code: 'PT', name: 'Portugal' },
    { code: 'PR', name: 'Puerto Rico' },
    { code: 'QA', name: 'Qatar' },
    { code: 'RE', name: 'Reunion' },
    { code: 'RO', name: 'Romania' },
    { code: 'RU', name: 'Russia' },
    { code: 'RW', name: 'Rwanda' },
    { code: 'BL', name: 'Saint Barthelemy' },
    { code: 'SH', name: 'Saint Helena' },
    { code: 'KN', name: 'Saint Kitts and Nevis' },
    { code: 'LC', name: 'Saint Lucia' },
    { code: 'MF', name: 'Saint Martin' },
    { code: 'PM', name: 'Saint Pierre and Miquelon' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines' },
    { code: 'WS', name: 'Samoa' },
    { code: 'SM', name: 'San Marino' },
    { code: 'ST', name: 'Sao Tome and Principe' },
    { code: 'SA', name: 'Saudi Arabia' },
    { code: 'SN', name: 'Senegal' },
    { code: 'RS', name: 'Serbia' },
    { code: 'SC', name: 'Seychelles' },
    { code: 'SL', name: 'Sierra Leone' },
    { code: 'SG', name: 'Singapore' },
    { code: 'SK', name: 'Slovakia' },
    { code: 'SI', name: 'Slovenia' },
    { code: 'SB', name: 'Solomon Islands' },
    { code: 'SO', name: 'Somalia' },
    { code: 'ZA', name: 'South Africa' },
    { code: 'GS', name: 'South Georgia and the South Sandwich Islands' },
    { code: 'SS', name: 'South Sudan' },
    { code: 'ES', name: 'Spain' },
    { code: 'LK', name: 'Sri Lanka' },
    { code: 'SD', name: 'Sudan' },
    { code: 'SR', name: 'Suriname' },
    { code: 'SJ', name: 'Svalbard and Jan Mayen' },
    { code: 'SZ', name: 'Swaziland' },
    { code: 'SE', name: 'Sweden' },
    { code: 'CH', name: 'Switzerland' },
    { code: 'SY', name: 'Syria' },
    { code: 'TW', name: 'Taiwan' },
    { code: 'TJ', name: 'Tajikistan' },
    { code: 'TZ', name: 'Tanzania' },
    { code: 'TH', name: 'Thailand' },
    { code: 'TL', name: 'Timor-Leste' },
    { code: 'TG', name: 'Togo' },
    { code: 'TK', name: 'Tokelau' },
    { code: 'TO', name: 'Tonga' },
    { code: 'TT', name: 'Trinidad and Tobago' },
    { code: 'TN', name: 'Tunisia' },
    { code: 'TR', name: 'Turkey' },
    { code: 'TM', name: 'Turkmenistan' },
    { code: 'TC', name: 'Turks and Caicos Islands' },
    { code: 'TV', name: 'Tuvalu' },
    { code: 'UG', name: 'Uganda' },
    { code: 'UA', name: 'Ukraine' },
    { code: 'AE', name: 'United Arab Emirates' },
    { code: 'GB', name: 'United Kingdom' },
    { code: 'US', name: 'United States' },
    { code: 'UY', name: 'Uruguay' },
    { code: 'UZ', name: 'Uzbekistan' },
    { code: 'VU', name: 'Vanuatu' },
    { code: 'VA', name: 'Vatican City' },
    { code: 'VE', name: 'Venezuela' },
    { code: 'VN', name: 'Vietnam' },
    { code: 'VG', name: 'Virgin Islands (British)' },
    { code: 'VI', name: 'Virgin Islands (US)' },
    { code: 'WF', name: 'Wallis and Futuna' },
    { code: 'EH', name: 'Western Sahara' },
    { code: 'YE', name: 'Yemen' },
    { code: 'ZM', name: 'Zambia' },
    { code: 'ZW', name: 'Zimbabwe' },
  ];

  private readonly nationalities: Nationality[] = [
    { code: 'AF', name: 'Afghan' },
    { code: 'AL', name: 'Albanian' },
    { code: 'DZ', name: 'Algerian' },
    { code: 'AS', name: 'American Samoan' },
    { code: 'AD', name: 'Andorran' },
    { code: 'AO', name: 'Angolan' },
    { code: 'AI', name: 'Anguillan' },
    { code: 'AQ', name: 'Antarctic' },
    { code: 'AG', name: 'Antiguan or Barbudan' },
    { code: 'AR', name: 'Argentine' },
    { code: 'AM', name: 'Armenian' },
    { code: 'AW', name: 'Aruban' },
    { code: 'AU', name: 'Australian' },
    { code: 'AT', name: 'Austrian' },
    { code: 'AZ', name: 'Azerbaijani' },
    { code: 'BS', name: 'Bahamian' },
    { code: 'BH', name: 'Bahraini' },
    { code: 'BD', name: 'Bangladeshi' },
    { code: 'BB', name: 'Barbadian' },
    { code: 'BY', name: 'Belarusian' },
    { code: 'BE', name: 'Belgian' },
    { code: 'BZ', name: 'Belizean' },
    { code: 'BJ', name: 'Beninese' },
    { code: 'BM', name: 'Bermudian' },
    { code: 'BT', name: 'Bhutanese' },
    { code: 'BO', name: 'Bolivian' },
    { code: 'BA', name: 'Bosnian' },
    { code: 'BW', name: 'Botswanan' },
    { code: 'BV', name: 'Bouvet Islander' },
    { code: 'BR', name: 'Brazilian' },
    { code: 'BN', name: 'Bruneian' },
    { code: 'BG', name: 'Bulgarian' },
    { code: 'BF', name: 'Burkinabe' },
    { code: 'BI', name: 'Burundian' },
    { code: 'KH', name: 'Cambodian' },
    { code: 'CM', name: 'Cameroonian' },
    { code: 'CA', name: 'Canadian' },
    { code: 'CV', name: 'Cape Verdean' },
    { code: 'KY', name: 'Caymanian' },
    { code: 'CF', name: 'Central African' },
    { code: 'TD', name: 'Chadian' },
    { code: 'CL', name: 'Chilean' },
    { code: 'CN', name: 'Chinese' },
    { code: 'CX', name: 'Christmas Islander' },
    { code: 'CC', name: 'Cocos Islander' },
    { code: 'CO', name: 'Colombian' },
    { code: 'KM', name: 'Comorian' },
    { code: 'CG', name: 'Congolese' },
    { code: 'CD', name: 'Congolese' },
    { code: 'CK', name: 'Cook Islander' },
    { code: 'CR', name: 'Costa Rican' },
    { code: 'HR', name: 'Croatian' },
    { code: 'CU', name: 'Cuban' },
    { code: 'CY', name: 'Cypriot' },
    { code: 'CZ', name: 'Czech' },
    { code: 'DK', name: 'Danish' },
    { code: 'DJ', name: 'Djiboutian' },
    { code: 'DM', name: 'Dominican' },
    { code: 'DO', name: 'Dominican' },
    { code: 'EC', name: 'Ecuadorian' },
    { code: 'EG', name: 'Egyptian' },
    { code: 'SV', name: 'Salvadoran' },
    { code: 'GQ', name: 'Equatorial Guinean' },
    { code: 'ER', name: 'Eritrean' },
    { code: 'EE', name: 'Estonian' },
    { code: 'ET', name: 'Ethiopian' },
    { code: 'FK', name: 'Falkland Islander' },
    { code: 'FO', name: 'Faroese' },
    { code: 'FJ', name: 'Fijian' },
    { code: 'FI', name: 'Finnish' },
    { code: 'FR', name: 'French' },
    { code: 'GF', name: 'French Guianan' },
    { code: 'PF', name: 'French Polynesian' },
    { code: 'TF', name: 'French Southern' },
    { code: 'GA', name: 'Gabonese' },
    { code: 'GM', name: 'Gambian' },
    { code: 'GE', name: 'Georgian' },
    { code: 'DE', name: 'German' },
    { code: 'GH', name: 'Ghanaian' },
    { code: 'GI', name: 'Gibraltar' },
    { code: 'GR', name: 'Greek' },
    { code: 'GL', name: 'Greenlandic' },
    { code: 'GD', name: 'Grenadian' },
    { code: 'GP', name: 'Guadeloupe' },
    { code: 'GU', name: 'Guamanian' },
    { code: 'GT', name: 'Guatemalan' },
    { code: 'GG', name: 'Guernseyite' },
    { code: 'GN', name: 'Guinean' },
    { code: 'GW', name: 'Guinea-Bissauan' },
    { code: 'GY', name: 'Guyanese' },
    { code: 'HT', name: 'Haitian' },
    { code: 'HK', name: 'Hong Kong' },
    { code: 'HU', name: 'Hungarian' },
    { code: 'IS', name: 'Icelandic' },
    { code: 'IN', name: 'Indian' },
    { code: 'ID', name: 'Indonesian' },
    { code: 'IR', name: 'Iranian' },
    { code: 'IQ', name: 'Iraqi' },
    { code: 'IE', name: 'Irish' },
    { code: 'IM', name: 'Manx' },
    { code: 'IL', name: 'Israeli' },
    { code: 'IT', name: 'Italian' },
    { code: 'CI', name: 'Ivorian' },
    { code: 'JM', name: 'Jamaican' },
    { code: 'JP', name: 'Japanese' },
    { code: 'JE', name: 'Jersey' },
    { code: 'JO', name: 'Jordanian' },
    { code: 'KZ', name: 'Kazakhstani' },
    { code: 'KE', name: 'Kenyan' },
    { code: 'KI', name: 'I-Kiribati' },
    { code: 'KP', name: 'North Korean' },
    { code: 'KR', name: 'South Korean' },
    { code: 'KW', name: 'Kuwaiti' },
    { code: 'KG', name: 'Kyrgyzstani' },
    { code: 'LA', name: 'Laotian' },
    { code: 'LV', name: 'Latvian' },
    { code: 'LB', name: 'Lebanese' },
    { code: 'LS', name: 'Sotho' },
    { code: 'LR', name: 'Liberian' },
    { code: 'LY', name: 'Libyan' },
    { code: 'LI', name: 'Liechtenstein' },
    { code: 'LT', name: 'Lithuanian' },
    { code: 'LU', name: 'Luxembourg' },
    { code: 'MO', name: 'Macanese' },
    { code: 'MK', name: 'Macedonian' },
    { code: 'MG', name: 'Malagasy' },
    { code: 'MW', name: 'Malawian' },
    { code: 'MY', name: 'Malaysian' },
    { code: 'MV', name: 'Maldivian' },
    { code: 'ML', name: 'Malian' },
    { code: 'MT', name: 'Maltese' },
    { code: 'MH', name: 'Marshallese' },
    { code: 'MQ', name: 'Martinique' },
    { code: 'MR', name: 'Mauritanian' },
    { code: 'MU', name: 'Mauritian' },
    { code: 'YT', name: 'Mahoran' },
    { code: 'MX', name: 'Mexican' },
    { code: 'FM', name: 'Micronesian' },
    { code: 'MD', name: 'Moldovan' },
    { code: 'MC', name: 'Monegasque' },
    { code: 'MN', name: 'Mongolian' },
    { code: 'ME', name: 'Montenegrin' },
    { code: 'MA', name: 'Moroccan' },
    { code: 'MZ', name: 'Mozambican' },
    { code: 'MM', name: 'Burmese' },
    { code: 'NA', name: 'Namibian' },
    { code: 'NR', name: 'Nauruan' },
    { code: 'NP', name: 'Nepalese' },
    { code: 'NL', name: 'Dutch' },
    { code: 'AN', name: 'Dutch' },
    { code: 'NC', name: 'New Caledonian' },
    { code: 'NZ', name: 'New Zealand' },
    { code: 'NI', name: 'Nicaraguan' },
    { code: 'NE', name: 'Nigerien' },
    { code: 'NG', name: 'Nigerian' },
    { code: 'NU', name: 'Niuean' },
    { code: 'NF', name: 'Norfolk Islander' },
    { code: 'MP', name: 'Northern Mariana Islander' },
    { code: 'NO', name: 'Norwegian' },
    { code: 'OM', name: 'Omani' },
    { code: 'PK', name: 'Pakistani' },
    { code: 'PW', name: 'Palauan' },
    { code: 'PS', name: 'Palestinian' },
    { code: 'PA', name: 'Panamanian' },
    { code: 'PG', name: 'Papua New Guinean' },
    { code: 'PY', name: 'Paraguayan' },
    { code: 'PE', name: 'Peruvian' },
    { code: 'PH', name: 'Philippine' },
    { code: 'PN', name: 'Pitcairn Islander' },
    { code: 'PL', name: 'Polish' },
    { code: 'PT', name: 'Portuguese' },
    { code: 'PR', name: 'Puerto Rican' },
    { code: 'QA', name: 'Qatari' },
    { code: 'RE', name: 'Reunionese' },
    { code: 'RO', name: 'Romanian' },
    { code: 'RU', name: 'Russian' },
    { code: 'RW', name: 'Rwandan' },
    { code: 'BL', name: 'Saint Barthelemy' },
    { code: 'SH', name: 'Saint Helenian' },
    { code: 'KN', name: 'Kittitian or Nevisian' },
    { code: 'LC', name: 'Saint Lucian' },
    { code: 'MF', name: 'Saint Martin' },
    { code: 'PM', name: 'Saint Pierre' },
    { code: 'VC', name: 'Vincentian' },
    { code: 'WS', name: 'Samoan' },
    { code: 'SM', name: 'Sammarinese' },
    { code: 'ST', name: 'Sao Tome' },
    { code: 'SA', name: 'Saudi' },
    { code: 'SN', name: 'Senegalese' },
    { code: 'RS', name: 'Serbian' },
    { code: 'SC', name: 'Seychellois' },
    { code: 'SL', name: 'Sierra Leonean' },
    { code: 'SG', name: 'Singaporean' },
    { code: 'SK', name: 'Slovak' },
    { code: 'SI', name: 'Slovenian' },
    { code: 'SB', name: 'Solomon Islander' },
    { code: 'SO', name: 'Somali' },
    { code: 'ZA', name: 'South African' },
    { code: 'GS', name: 'South Georgia' },
    { code: 'SS', name: 'South Sudanese' },
    { code: 'ES', name: 'Spanish' },
    { code: 'LK', name: 'Sri Lankan' },
    { code: 'SD', name: 'Sudanese' },
    { code: 'SR', name: 'Surinamese' },
    { code: 'SJ', name: 'Svalbard Islander' },
    { code: 'SZ', name: 'Swazi' },
    { code: 'SE', name: 'Swedish' },
    { code: 'CH', name: 'Swiss' },
    { code: 'SY', name: 'Syrian' },
    { code: 'TW', name: 'Taiwanese' },
    { code: 'TJ', name: 'Tajikistani' },
    { code: 'TZ', name: 'Tanzanian' },
    { code: 'TH', name: 'Thai' },
    { code: 'TL', name: 'Timorese' },
    { code: 'TG', name: 'Togolese' },
    { code: 'TK', name: 'Tokelauan' },
    { code: 'TO', name: 'Tongan' },
    { code: 'TT', name: 'Trinidad and Tobagonian' },
    { code: 'TN', name: 'Tunisian' },
    { code: 'TR', name: 'Turkish' },
    { code: 'TM', name: 'Turkmenistani' },
    { code: 'TC', name: 'Turks and Caicos Islander' },
    { code: 'TV', name: 'Tuvaluan' },
    { code: 'UG', name: 'Ugandan' },
    { code: 'UA', name: 'Ukrainian' },
    { code: 'AE', name: 'Emirati' },
    { code: 'GB', name: 'British' },
    { code: 'US', name: 'American' },
    { code: 'UY', name: 'Uruguayan' },
    { code: 'UZ', name: 'Uzbekistani' },
    { code: 'VU', name: 'Vanuatu' },
    { code: 'VA', name: 'Vatican' },
    { code: 'VE', name: 'Venezuelan' },
    { code: 'VN', name: 'Vietnamese' },
    { code: 'VG', name: 'Virgin Islander' },
    { code: 'VI', name: 'Virgin Islander' },
    { code: 'WF', name: 'Wallis and Futuna Islander' },
    { code: 'EH', name: 'Sahrawi' },
    { code: 'YE', name: 'Yemeni' },
    { code: 'ZM', name: 'Zambian' },
    { code: 'ZW', name: 'Zimbabwean' },
  ];

  /**
   * Get all countries
   */
  getCountries(): Country[] {
    return [...this.countries];
  }

  /**
   * Get all nationalities
   */
  getNationalities(): Nationality[] {
    return [...this.nationalities];
  }

  /**
   * Get country by code
   */
  getCountryByCode(code: string): Country | undefined {
    return this.countries.find(c => c.code === code);
  }

  /**
   * Get nationality by code
   */
  getNationalityByCode(code: string): Nationality | undefined {
    return this.nationalities.find(n => n.code === code);
  }

  /**
   * Get country name by code
   */
  getCountryName(code: string): string {
    const country = this.getCountryByCode(code);
    return country ? country.name : code;
  }

  /**
   * Get nationality name by code
   */
  getNationalityName(code: string): string {
    const nationality = this.getNationalityByCode(code);
    return nationality ? nationality.name : code;
  }
}
